name: 'Deploy to AWS S3'
description: 'Deploy to AWS S3 w Docker'
inputs:
  bucket:
    description: 'S3 bucket name'
    required: true
  bucket-region:
    description: 'S3 bucket region'
    required: true
  dist-folder:
    description: folder containing files to deploy
    required: true
outputs:
  web-url:
    description: 'url of the deployed website'
runs:
  using: 'docker'
  image: 'Dockerfile'