name: 'Get and Cache Dependencies'
description: 'Get deps via npm and cache'
inputs:
  caching:
    description: 'whether to cache deps'
    required: false
    default: 'true'
outputs:
  cache-used:
    description: 'output example'
    value: ${{ steps.step-id.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true' 
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "cache='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
      shell: bash