# This is a basic workflow to help you get started with Actions

name: test workflow
on: workflow_dispatch #Controls when the workflow will run
jobs: #one or more jobs that can run sequentially or in parallel
  # This workflow contains a single job called "build"
  testjob:
    runs-on: ubuntu-20.04 #runner that the job will run on. search github actions runners for labels
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v3
      - name: test step
        run: echo Hello, world!
