name: test workflow
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Get Project Code
      - uses: actions/checkout@v3
      - name: Install Deps
        run: npm ci
      - name: Run Tests
        run: npm test
